/******************************************************************************
 *  * 
 *    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
 *    Source Project Contributors and others.
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0

 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_TransitionEffectManagerCallback */

#ifndef _Included_org_allseen_lsf_TransitionEffectManagerCallback
#define _Included_org_allseen_lsf_TransitionEffectManagerCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_TransitionEffectManagerCallback
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectManagerCallback_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_TransitionEffectManagerCallback
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_TransitionEffectManagerCallback_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
