/******************************************************************************
 * Copyright (c) AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PulseEffect */

#ifndef _Included_org_allseen_lsf_PulseEffect
#define _Included_org_allseen_lsf_PulseEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setToLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setToLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getToLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffect_getToLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setFromLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setFromLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getFromLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffect_getFromLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setToPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setToPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getToPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffect_getToPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setFromPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setFromPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getFromPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffect_getFromPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setPulsePeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setPulsePeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getPulsePeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffect_getPulsePeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setPulseDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setPulseDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getPulseDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffect_getPulseDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    setNumPulses
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_setNumPulses
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    getNumPulses
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffect_getNumPulses
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffect
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffect_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
